name: Node.js CI/CD for Development Branch [Jsonrock Backend Softcolon]

on:
  push:
    branches: ['development']

jobs:
  build:
    runs-on: be-jsonrock dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Add Envrionemnt Variables
        run: cp /home/ankit/projects/be-jsonrock-dev/.env .env

      - name: Install Dependencies
        run: pnpm install

      - name: Build Application
        run: pnpm build

      - name: Restart Application with PM2
        run: pm2 restart be-jsonrock-dev
